### ISSUE TITLE
Suggestion for another example of query code 

### ISSUE THREAD

**Issue by matthewbretherton** [nolim1t/btcmarkets-gem#3]
You may wish to add this example into of code to your 'Sample Code' section

puts b.post_order_open( {"currency":"AUD","instrument":"BTC","limit":10,"since":0})

on the https://github.com/nolim1t/btcmarkets-gem page

It offers an example of a post with parameters and may save people reading the code closely to understand the mapping within method missing to a well formed request

Rgds
matthew@bretherton.id.au

PS I posted this to the central issues site and the support folks at BTC advised to post directly here

**Comment by nolim1t** [comment]
Thanks for the feedback.  I've incorporated your suggestion in there.

I haven't actually maintained this gem for a while but glad it still works. Help with documentation is defintetely appreciated.
